apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
  namespace: dev-space
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend-dev
          image: vishathamarasinghe/gathernexus-frontend-dev:latest  # Docker image for the API Gateway
          ports:
            - containerPort: 80  # Port exposed inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
  namespace: dev-space
spec:
  selector:
    app: frontend-dev  # This will select pods with label 'app=frontend-stg'
  ports:
    - protocol: TCP
      port: 5601  # Exposing port 5601 on the service
      targetPort: 80  # The port the container is listening on
  type: ClusterIP  # exposes the service internally within the cluster
